package vista;

public enum Opcion {
	SALIR, INSERTAR_CLIENTE, INSERTAR_TURISMO, INSERTAR_ALQUILER, BUSCAR_CLIENTE, BUSCAR_TURISMO, BUSCAR_ALQUILER,
	MODIFICAR_CLIENTE, DEVOLVER_ALQUILER, BORRAR_CLIENTE, BORRAR_TURISMO, BORRAR_ALQUILER, LISTAR_CLIENTES,
	LISTAR_TURISMOS, LISTAR_ALQUILERES, LISTAR_ALQUILERES_CLIENTE, LISTAR_ALQUILERES_TURISMO;
}
